### ISSUE TITLE
Switch to github actions over travis

### ISSUE THREAD

**Issue by jrideout** [koodaamo/tnefparse#107]
We are doing builds in both places now. Should we just use github instead?

**Comment by jugmac00** [comment]
Travis does no longer support open source projects, but only gave one time 10000 credits (or build minutes), and once they are used up, you are on a mission impossible to get new credits.

Looks like all other open source projects I know go with GitHub Actions.

I see no reason to use Travis CI any longer.

**Comment by jugmac00** [comment]
Working on  a PR to remove it.
