### ISSUE TITLE
Release 1.4

### ISSUE THREAD

**Issue by jrideout** [koodaamo/tnefparse#108]
We have a bunch of changes ready to go for 1.4. Should anything else be included, or are we ready to ship?

**Comment by jugmac00** [comment]
Maybe you could review #109 and then we are good to go imho.

**Comment by jrideout** [comment]
@petri I'd be happy to upload to pypi if you want to add me to the package. My username on pypi.org is `jacobrideout`

**Comment by petri** [comment]
Ok I'll cut a release, probably tomorrow or Monday.

**Comment by petri** [comment]
Will upload to PyPi later today. [1.4.0](https://github.com/koodaamo/tnefparse/tree/1.4.0) tagged. Master is back to dev.

**Comment by petri** [comment]
Done https://pypi.org/project/tnefparse/1.4.0/
