### ISSUE TITLE
Push new version to PyPI

### ISSUE THREAD

**Issue by tonyandrewmeyer** [koodaamo/tnefparse#11]
Hi! Thanks for building this library; it's very handy :smile:.

Do you think that you'd be able to push a new build to PyPI? It would be get to be able to `pip install` (without linking to a GitHub revision) the code that has the latest fixed.

**Comment by mlaferrera** [comment]
Any word on when this can happen? The master branch has plenty of fixes that would be useful.

**Comment by petri** [comment]
done
