### ISSUE TITLE
decode_mapi exception

### ISSUE THREAD

**Issue by dgouldin** [koodaamo/tnefparse#13]
When using `decode_mapi`, I get the following error with the logger level set to `DEBUG`:

`'int' object has no attribute '__getitem__'`

After poking at the source to prevent it swallowing the stack trace of the error, it looks as though it's coming from:

https://github.com/koodaamo/tnefparse/blob/137e7d23a3bfa80296504c4f41f9b1471d686b96/tnefparse/mapi.py#L81

(That makes sense to me, given that `offset` is an int.)

Apologies, I don't know the subject matter well enough to propose a fix.

**Comment by petri** [comment]
Can you share the TNEF file you are using that produces this logger debug error?

**Comment by nikiladonya** [comment]
@petri  Hello, file called "two-files.tnef" in your tests raise this error (3 python)

**Comment by petri** [comment]
@nikiladonya can you provide example code to raise the error?

**Comment by petri** [comment]
This should now be fixed in master.

**Comment by petri** [comment]
By the way, the debug code is really old and should be cleaned. It is very possible that setting log level to DEBUG exposes some bugs in debugging parts of the code itself. If you find an issue that is an actual problem for you, please submit a new issue.
