### ISSUE TITLE
TNEFMAPI_Attribute for attachment content-id

### ISSUE THREAD

**Issue by TZanke** [koodaamo/tnefparse#14]
in Mail HTML embedded images are references by content-id. At the moment i could not find this value by TNEFMAPI_Attribute class. So i searched in the mapi_attrs. The content-id attribute has the name '14098' => 0x3712

Should 0x3712 added to the TNEFMAPI_Attribute class?

**Comment by petri** [comment]
Sounds ok. Could you provide a pull request with a link pointing to relevant documentation?

**Comment by petri** [comment]
How is this different from MAPI_CONTENT_IDENTIFIER (0x0008) ?

**Comment by petri** [comment]
Looks like the definition for 0x3712 is here: https://msdn.microsoft.com/en-us/library/office/cc765868.aspx

**Comment by TZanke** [comment]
I created this file last summer with Outlook 2010 / Microsoft Outlook 14.0 as a test file for special chars and attachments.
[winmail.dat.zip](https://github.com/koodaamo/tnefparse/files/1775119/winmail.dat.zip)

At the moment i use the `14098`  to get the content id `image003.jpg@01D2EE6A.85652C70`

**Comment by jrideout** [comment]
This was fixed in b21d36e189e590c7cb44e204e75bed49e08764f4

**Comment by petri** [comment]
@TZanke see above comment. Closing.
