### ISSUE TITLE
Cannot pull ics file

### ISSUE THREAD

**Issue by dugite-code** [koodaamo/tnefparse#16]
Python: 3.5.3
tnefparse installed from pip
Windows 10

I'm trying to parse a winmail.dat file from a appointment invite email. Using lookout (fix version) in thunderbird I can see a rtf file, the ics file and a vcf file. Using:

```
    for part in msg.walk():
        if part.get_content_type() == 'application/ms-tnef':
            tnef = TNEF( part.get_payload( decode=True ) )
            for attachment in tnef.attachments:
                print(attachment.name)
```

I get this output:
```
WARNING:tnef-decode:Unknown TNEF Object: <TNEFObject 'TNEF Version'>
WARNING:tnef-decode:Unknown TNEF Object: <TNEFObject 'OEM Codepage'>
WARNING:tnef-decode:Unknown TNEF Object: <TNEFObject 'Message ID'>
WARNING:tnef-decode:Unknown TNEF Object: <TNEFObject 'Priority'>
WARNING:tnef-decode:Unknown TNEF Object: <TNEFObject 'Date Sent'>
WARNING:tnef-decode:Unknown TNEF Object: <TNEFObject 'Date Modified'>
WARNING:tnef-decode:Unknown TNEF Object: <TNEFObject 'Message Class'>
WARNING:tnef-decode:Unknown TNEF Object: <TNEFObject 'Subject'>
WARNING:tnef-decode:Unknown TNEF Object: <TNEFObject 'Date Start'>
WARNING:tnef-decode:Unknown TNEF Object: <TNEFObject 'Date End'>
WARNING:tnef-decode:Unknown TNEF Object: <TNEFObject 'Owner Appointment ID'>
WARNING:tnef-decode:Unknown TNEF Object: <TNEFObject 'Response Requested'>
```

It looks like the calendar is being parsed as TNEF Objects. Any advice?

**Comment by petri** [comment]
Is that all the output you got? Your code should show the attachment names as well.

If not, can you share your winmail.dat file here so that I could take a look?

What it comes to the warnings, well, tnefparse logging is a bit of a mess, please see #18. If you can add some suggestions there, it'd be helpful.

**Comment by jrideout** [comment]
@dugite-code Do you still have any issues we can help you with?

**Comment by dugite-code** [comment]
Possibly not? The Thunderbird's lookout plugin did pull files out but it looks like it may have been a simple case of a corrupted file, a random zero width character was getting printed out in the [lookout logs](https://github.com/TB-throwback/LookOut-fix-version/issues/3) so that might have been the source of my issues.

![image](https://user-images.githubusercontent.com/12742064/43826865-fd4d582a-9b2a-11e8-9a17-1e775ba95cec.png)

I'll give tnefparse another go at some point soon since there have been a couple of updates since then
