### ISSUE TITLE
Using `range` in Python 2 causes memory issues

### ISSUE THREAD

**Issue by cosmingrz** [koodaamo/tnefparse#21]
While parsing some corrupted TNEF files the code below can hang and use large amounts of memory:
```
num_vals = bytes_to_int(data[offset:offset+4]); offset += 4

#            logger.debug("Number of values: %i" % num_vals)
            attr_data = []
            for j in range(num_vals):
```

In my example `num_vals` is for some reason  `3666903040` and the parser is using large amounts of memory until statement is evaluated. On other machines with low ammount of RAM, parser just raises `MemoryError` after a while.

The solutuion would be to use `xrange` for those loops  if the script is running in Python 2.

**Comment by petri** [comment]
Cherry-picked the switch to xrange on Python2.
