### ISSUE TITLE
nullbytes in data

### ISSUE THREAD

**Issue by TZanke** [koodaamo/tnefparse#24]
I try to get some tnef data information, but atm i have to remove nullbytes by myself.
Is there a other way to get the same information without nullbytes, or is this is a bug?

      for tnef_attachment in tnef.attachments:
                for mapi_attr in tnef_attachment.mapi_attrs:
                    if mapi_attr.name == tnefparse.TNEFMAPI_Attribute.MAPI_ATTACH_MIME_TAG:
                        mimetype = mapi_attr.data[0].rstrip(b'\x00')

**Comment by petri** [comment]
Is this on PyPI release or current master?

**Comment by TZanke** [comment]
correction:
has traling null also in Ubuntu tested with master.

[tnef_with_umlaut.eml.zip](https://github.com/koodaamo/tnefparse/files/2623671/tnef_with_umlaut.eml.zip)
