### ISSUE TITLE
Inconsistent line endings

### ISSUE THREAD

**Issue by jrideout** [koodaamo/tnefparse#32]
Can we adopt some code standards?

In particular I'd like to suggest:
 - unix line endings are used consistently
 - 4 spaces for the default indent

More aggressively we could use something like `black` to auto-format the style.

**Comment by petri** [comment]
Absolutely. The codebase is really old, originally a quick & dirty conversion from Ruby code with not much thought given to code quality at that time.

**Comment by jrideout** [comment]
Fixed in #37
