### ISSUE TITLE
switch to "plain" pytest

### ISSUE THREAD

**Issue by petri** [koodaamo/tnefparse#33]
We have old pytest integration with a setup.py subcommand and a versioned "runtests.py". This is deprecated and giving some trouble on Python2.

Suggest we remove this and just use pytest from now on.

**Comment by petri** [comment]
@jrideout switched to using pytest-runner. Local tests still runnable as `python setup.py test'.

btw there's also test coverage now at https://codecov.io/gh/koodaamo/tnefparse

**Comment by jrideout** [comment]
This didn't work for me.

I had to install `pytest-console-scripts` too.

**Comment by petri** [comment]
sorry, forgot to add that as a requirement somewhere... added it to setup_requires, too, for now.
