### ISSUE TITLE
Release 1.3

### ISSUE THREAD

**Issue by jrideout** [koodaamo/tnefparse#43]
What needs to be done?

- Tag
- Publish to http://pypi.org

Anything else?

**Comment by jrideout** [comment]
Blocked on #44

**Comment by petri** [comment]
Update HISTORY

**Comment by jrideout** [comment]
I added a few items, but otherwise I think we are good to release!

**Comment by petri** [comment]
released 1.3.0

**Comment by petri** [comment]
Oh and btw @jrideout thanks for the nice work!
