### ISSUE TITLE
Should we rename PID_TAG_  constants?

### ISSUE THREAD

**Issue by jrideout** [koodaamo/tnefparse#44]
PidTag or PidLid are the naming conventions MS uses, so I used the same when adding a bunch of properties outside the core MAPI types.

I'm thinking though, we just call everything `MAPI_` for consistency. We'll want to decide this before publishing 1.3.

**Comment by petri** [comment]
Stay consistent with the TNEF / MAPI docs (if feasible; I don't know if the docs themselves are consistent on this), and just add a comment pointing out that PidTag or PidLid are just MAPI types with a different naming convention?

Just a thought; no strong opinion either way.

**Comment by jrideout** [comment]
To stay consistent we'd want to rename the _existing_  MAPI_* types to PID_TAG, which would probably break existing applications. Given that, I'm going to just cover it all to MAPI_ and then add a comment like you suggest.

**Comment by petri** [comment]
> To stay consistent we'd want to rename the _existing_ MAPI_* types to PID_TAG, which would probably break existing applications. 

I see. We can consider doing that in a controlled manner over a few releases at some later time I guess.
