### ISSUE TITLE
Logging logger not registered when used as module

### ISSUE THREAD

**Issue by ericavijay** [koodaamo/tnefparse#51]
Looks like the tnef.py when not using command line but used as a library has not initiated logging with logging.basicConfig() so when I import it and there is any issue the logger throws an output like 
No handlers could be found for logger "tnef-decode"

Recommended changes to init.py to initiate logging. It seems to happen only in cmline.py - useful only when using command line.  It will be helpful for this to happen earlier so importing of tnefparse can work without this error!

Here is my recommend diff for __init__.py 

***************
*** 1,4 ****
--- 1,6 ----
  import warnings
+ import logging
+ logging.basicConfig()

**Comment by petri** [comment]
Thanks. This should now be fixed so closing.
