### ISSUE TITLE
Filenames are truncated

### ISSUE THREAD

**Issue by skylord123** [koodaamo/tnefparse#53]
When you run with the `--attachments` argument the files are using the truncated name instead of the full name. This is a problem for my use case. Can we either get an option to use the long_filename or just make this the default?

In my example the filename was `decemberpermits14.pdf` but was being truncated to `decemb~1.pdf`.

Thanks!

**Comment by Beercow** [comment]
Submitted a pull request to fix this. Try it and let me know if it works for you.

**Comment by skylord123** [comment]
Works perfectly. File names are no longer truncated.

Thanks for the quick help!

**Comment by skylord123** [comment]
I saw some extra commits on your pull request, are these an attempt to fix #52 ?

**Comment by Beercow** [comment]
Yes. The other commits are to fix #52 also. I have tested this on Windows and python 2.7.15. I have not tested it with python 3.

**Comment by petri** [comment]
Thanks. PR merged.
