### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by amit777** [koodaamo/tnefparse#57]
Hi there, first thank you for this incredibly useful tool.  I really love the JSON export feature but just realized it's not released in the main pip install.  Any tips on when to expect it?

**Comment by petri** [comment]
I will try to find some time to cut a release.

**Comment by petri** [comment]
@jugmac00 do you want to add something before we cut a release, or have something new as part of release process? I've usually just generated source & wheel dists & uploaded to PyPI.

**Comment by jugmac00** [comment]
@petri There is not much too add - maybe except a `MANIFEST` change - see below.

We only have two open issues, the release :dancers: itself and adding typing.

Having typed three projects lately (two from scratch, and one had to be fixed + converted from type comments to type annotations), I can say...
- there are type comments to type annotations converters, which work okish -> so better start typing when Python 2 support had been dropped (no hurry)
- typing starts to make "fun" with Python 3.6, but with every new release, it gets better
- I really enjoy working on a typed project (less bugs, better IDE support, easier reasoning...)
- I need a little break from typing complete projects :-), its pretty exhausting

About the release process, the last year or so I started to follow my release process after this blog post: 
https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/

It is basically the same story - build packages - upload them.

There is one thing, you could have a look at.

There is a great tool, called `check-manifest`, and when I run it on this project, it adds some suggestions:

```
❯ check-manifest 
lists of files in version control and sdist do not match!
missing from sdist:
  cmdline.py
  data/properties.txt
  scripts/make_props.py
suggested MANIFEST.in rules:
  include *.py
  recursive-include data *.txt
  recursive-include scripts *.py
```

(`pip install check-manifest` and execute the binary while in the root of this project / https://github.com/mgedmin/check-manifest)

If you are ok, I'd fix these issues by applying the suggested MANIFEST changes.

I also usually add `check-manifest` as a tox env.

Just in case you want me to be able to also do releases in the future, it would be great if you take down some notes how you do releases, so I could do it the same way.

**Comment by jugmac00** [comment]
PR see #72

**Comment by petri** [comment]
Released.
