### ISSUE TITLE
TNEF is throwing an error for python version 3.7.3

### ISSUE THREAD

**Issue by Sam-Gracy** [koodaamo/tnefparse#62]
Hi Team,

Such a great and wonderful tool to parse TNEF files. I am using python 2.7 and it is working excellent, few days back I upgraded to 3.7.3 and I am seeing this exception.

Traceback (most recent call last):
  File "TNEFParser.py", line 99, in readTNEFFiles
    t = TNEF(open(filename).read(), do_checksum=True) ## filename is winmail.dat
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9f in position 1: invalid start byte

Could you please help me to understand the issue

**Comment by Sam-Gracy** [comment]
Replaced t = TNEF(open(filename).read(), do_checksum=True)
With t = TNEF(open(filename, 'rb').read(), do_checksum=True) and the issue is fixed.

**Comment by jugmac00** [comment]
Hi @Sam-Gracy 
I am not a member of the team, but found this great package recently and use it also on Python 3 - with no problems so far.

When I have a look at your code, I think the problem is not this library, but your call to open/read.

Update - oh well - you were faster :-D

**Comment by petri** [comment]
I guess this can then be closed. Thanks @jugmac00 .
