### ISSUE TITLE
Flake8

### ISSUE THREAD

**Issue by jugmac00** [koodaamo/tnefparse#66]
Flake8 is currently only used in GitHub actions.

I'd like to introduce a `tox` environment for Flake8.

Currently, there would be 78 Flake8 errors when I apply very strict rules.

While the most errors are pretty straight forward to fix, before I start I both wanted to know your take on it in general and especially E221 (multiple spaces before operator).

E221 would mark following code as erroneously formatted:

https://github.com/koodaamo/tnefparse/blob/6a02c0b59497b681fecf902ab565580b9899ff10/tnefparse/mapi.py#L30-L50

So, before I start. Is applying Flake8 welcome? Is is ok to re-format above code? If not - do you prefer noqa annotations per line or ignore E221 altogether?

Is it ok to enforce Flake8 via Travis / GitHub actions?

**Comment by petri** [comment]
I think E221 should be enforced, but not religiously. To me, the MAPI constants module is cleaner with the "column" - based approach. I think Flake8 had a way to exclude a whole module from a particular check such as this?

**Comment by jugmac00** [comment]
TIL: There is an option to ignore a specific violation per file, but not in the file itself, but via configuration - looks a bit clunky to me and it does not seem to be bug-free either https://gitlab.com/pycqa/flake8/-/issues/517

I'd prefer the line specific annotation.

```
per-file-ignores =
    project/__init__.py:F401
    setup.py:E121
    other_project/*:W9
```
