### ISSUE TITLE
tnef_attachement.name is not unicode

### ISSUE THREAD

**Issue by guettli** [koodaamo/tnefparse#7]
I get a UnicodeError in my application code, because tnef_attachement.name is not unicode.

Could the tnef library get updated, to make tnef_attachement.name a unicode string?

In my case it looks like a latin1 string. It would improve the usability of the library if the application programmer does not need to do string decoding.

Sorry, I can't post the tnef binary, since it is from a customer.

BTW, how can you create tnef test binaries?

**Comment by plq** [comment]
fixed in 59dbf77a88476c6222fd1eeb78fe15768a6a554c

**Comment by guettli** [comment]
Unfortunately I don't have the matching test here to proof if the patch solves this issue.

I trust you and I think this issue can be closed.

Should I close it?

**Comment by plq** [comment]
I'm not in position to make that decision.

**Comment by petri** [comment]
Please, if you can, provide a PR.

**Comment by petri** [comment]
Note: master now strips null bytes from long_filename as well.

**Comment by petri** [comment]
The encoding of tnef attachment (long) names is a bit tricky to get right, it's not exactly simple.

See for example the discussion at https://github.com/roundcube/roundcubemail/issues/5646 .

If you have good understanding of how the encodings in tnef attachments work or any links to information, that would help.

**Comment by petri** [comment]
Note: we should also consider how this is to work on Python2 vs. Python3 (with help of six?)

**Comment by jrideout** [comment]
This should be addressed by #31

**Comment by guettli** [comment]
thank you!
