### ISSUE TITLE
Extract MAPI_ATTACH_METHOD == 5 parts?

### ISSUE THREAD

**Issue by albrechtd** [koodaamo/tnefparse#74]
I got a few (malicious) messages with `winmail.dat` attachments which `tnefparse` cannot extract.  The JSON dump produced by it contains, inter alia
```
    "attachments": [
        {
            "MAPI_ATTACH_METHOD": 5,
            "MAPI_CREATION_TIME": "2020-10-10 14:57:44.056806",
            "MAPI_LANGUAGE": "EnUs",
            "MAPI_LAST_MODIFICATION_TIME": "2020-10-10 14:57:44.056806",
            "MAPI_RENDERING_POSITION": -1,
            "data_len": 1,
            "filename": "",
            "long_filename": ""
        }
    ],
```
However, the part is ~170 kBytes, and running `unzip` on it extracts at least parts parts of a (malware) M$ Office document starting at offset ~32 kBytes. 
I found a note that MAPI attach method 5 indicates a “message”, whatever this means in this context.  Is it generally impossible to extract such items (also, neither [tnef](https://packages.debian.org/buster/tnef) nor [ytnef-tools](https://packages.debian.org/buster/ytnef-tools) produce usable output), or would it be possible to add it to `tnefparse`?

Thanks in advance, Albrecht.

**Comment by petri** [comment]
Could you provide a link to the note you found please?

**Comment by albrechtd** [comment]
> Could you provide a link to the note you found please?

I found this information: http://www.mimekit.net/docs/html/T_MimeKit_Tnef_TnefAttachMethod.htm – unfortunately, there are no references where these constants are actually specified.  However, as the author has a microsoft.com email address, this *might* be an indication that he has more information than available to the public…

> Also, please clarify; you say tnefparse cannot extract the part - yet you indicate you have been somehow able to extract it since you know it's size and were able to unzip it? How did you extract it?

Umm, sorry, my description was somewhat short…

The file I try to open is a `winmail.dat` attachment of a RFC 5322 message.  Saving it and running
```
tnef --number-backups --save-body=tnef-body --body-pref=ALL --ignore-checksum \
    --ignore-encode --ignore-cruft -C $(pwd)/out_tnef winmail.dat
```
produces a single output file `tnef-tmp` which `file` classifies as “data” (application/octet-stream).

Apparently, as no attachment file names are present (see the output in my original post), running `tnefparse` for extracting the attachments ejects with an error:
```
albrecht@deneb:~/Work$ /home/albrecht/.local/bin/tnefparse -a -p $(pwd)/out_tnefparse winmail.dat
Traceback (most recent call last):
  File "/home/albrecht/.local/bin/tnefparse", line 10, in <module>
    sys.exit(tnefparse())
  File "/home/albrecht/.local/lib/python2.7/site-packages/tnefparse/cmdline.py", line 95, in tnefparse
    with open(pth + a.long_filename(), "wb") as afp:
IOError: [Errno 21] Is a directory: u'/home/albrecht/Work/out_tnefparse/'
```
Running `unzip` on `winmail.dat` apparently finds the M$ OOXML malware:
```
albrecht@deneb:~/Work$ unzip -l winmail.dat
Archive:  winmail.dat
warning [winmail.dat]:  33833 extra bytes at beginning or within zipfile
  (attempting to process anyway)
  Length      Date    Time    Name
---------  ---------- -----   ----
     2010  1980-01-01 00:00   [Content_Types].xml
[…]
```

Running `unzip` on `tnef-tmp` produced by calling `tnef` also finds the document, just with a different offset.

**Comment by jrideout** [comment]
@albrechtd can you post the winmail.dat file somewhere so we can investigate?

**Comment by RossPatterson** [comment]
I have a similar case, but instead of malicious code, what was sent was an Outlook distribution list (an IPM.DistList).  `tnefparse -d filename` shows the attachment, but `tnefparse -a filename` gets an odd error: 

```
Traceback (most recent call last):
  File "<pyshell#36>", line 1, in <module>
    tnefparse.cmdline.tnefparse(['-a', 'ross_file'])
  File "C:\Ross\Source\tnefparse\tnefparse\cmdline.py", line 101, in tnefparse
    afp.write(a.data)
TypeError: a bytes-like object is required, not 'list'
```

`a.data` has somehow become a single-element array.  The actual attachment appears to be in `a.data[0]`

The original file is safe to share (it's not malicious), so I can post it somewhere (dunno where to put a binary file, though).

**Comment by jrideout** [comment]
@RossPatterson thanks, can you create a PR adding the file to https://github.com/koodaamo/tnefparse/tree/master/tests/examples ?

**Comment by RossPatterson** [comment]
Done.  Please merge.

Ross

**Comment by jrideout** [comment]
We'll track the fix in https://github.com/koodaamo/tnefparse/pull/101

**Comment by jrideout** [comment]
@albrechtd Can you please test your file with the code from this branch #101 ?  The json dump should give you the details of the embedded message.

**Comment by RossPatterson** [comment]
The #101 branch code successfully dumps and extracts the un-redacted
distribution list from my case.  Attempting to dump the extracted
IPM.DistList attachment (via tnefparse -d "Unititled Attachment") gets "Wrong
TNEF signature: 0x00020307", but that might be the correct behavior - I
have no idea if that file is TNEF, or some other format.

Ross

**Comment by jrideout** [comment]
The first 16 bytes are extra metadata defining the "interface" of the file. Presuming they match the magic numbers for a "message interface," then you can presume the remaining data in the file is a valid tnef. 

What do you suggest the behavior be for extracting the attachment? Should we just strip the first 16 bytes? This is what I'm doing for the json dump case. The tradeoff is that you are losing information, but I suspect it is better to just get the most parsable file possible.

**Comment by albrechtd** [comment]
Hi,
first, I think I should apologise for not posting my sample – an inspection of the included malware doc revealed that is was actually an Emotet file.  This campaign is known for re-using stolen messages for “fake” replies.  Therefore, I asked the recipient for permission for sharing the attachment, and she declined as the feared that private information would be publicly available on the internet.  Of course, I have to respect that!

> @albrechtd Can you please test your file with the code from this branch #101 ? The json dump should give you the details of the embedded message.

Actually, your solution *almost* does the job.  The only issue is that the `long_filename()` element of the attachment (identified as `embedded_message` when running `tnefparse -d`) is empty, leading to a crash.  Using the following patch (slightly paranoid, just in case that more than one attachment without a file name exists)
```
--- tnefparse-master.orig/tnefparse/cmdline.py  2021-01-22 16:11:22.000000000 +0100
+++ tnefparse-master/tnefparse/cmdline.py       2021-01-22 18:19:42.181741987 +0100
@@ -96,8 +96,14 @@
 
         elif args.attachments:
             pth = args.path.rstrip(os.sep) + os.sep if args.path else ''
+            idx = 1
             for a in t.attachments:
-                with open(pth + a.long_filename(), "wb") as afp:
+                if a.long_filename():
+                    outname = pth + a.long_filename()
+                else:
+                    outname = pth + '__unknown_' + str(idx) + '__'
+                    idx += 1
+                with open(outname, "wb") as afp:
                     afp.write(a.data)
             sys.stderr.write(f"Successfully wrote {len(t.attachments)} files\n")
             sys.exit()
```
a file `__unknown_1__` is dumped which again is a tnef, apparently a complete message.  Running `tnefparse` again on this dump properly extracts the Emotet doc file.
Good work!
Thanks a lot, Albrecht.
