### ISSUE TITLE
Drop support for Python 2.7 (and 3.5)

### ISSUE THREAD

**Issue by jugmac00** [koodaamo/tnefparse#75]
The build currently breaks on Python 2.7, as a transitive dep is no longer Python 2.7 compatible.

While we could pin the dependency, maybe it is about time to move forward?

**Comment by petri** [comment]
Yes, why not. Anyone needing Python2 support will be able to just use 1.3.1.

**Comment by petri** [comment]
Builds pass again. Metadata, build configs and docs changed to indicate Python3 only status from now on. There's things we still could & should do I am sure so not closing this yet. 

But since some badges use pypi as a source of truth, should preferably push a release sooner rather than later.

**Comment by jugmac00** [comment]
I have a bit of spare time tomorrow. I will look into this. Also, I'd like to run https://github.com/asottile/pyupgrade on the source code.

What is your take on support for Python 3.5? It is EOL since September. Python 3.6 brought f-strings, and also typing (#50) is more convenient with Python 3.6+ as then type annotations for variables were introduced.

**Comment by petri** [comment]
> What is your take on support for Python 3.5? It is EOL since September. Python 3.6 brought f-strings, and also typing (#50) is more convenient with Python 3.6+ as then type annotations for variables were introduced.

I would say let's require 3.6+ while we're at it.
